#!/usr/bin/env python3
"""Emit the newamp VQ codebooks as a flat binary for CODEC2_EXTERNAL_CODEBOOKS.

Builds with -DCODEC2_EXTERNAL_CODEBOOKS leave the tables out of the image and
expect them in memory-mapped storage instead - on nRF52840 that is external
QSPI flash at 0x12000000, live as soon as nrfx_qspi_init() activates it.

  python3 tools/make_codebook_blob.py src codec2-codebooks.bin
  python3 tools/make_codebook_blob.py src codebook_blob.h --c-array

The UF2 bootloader on nRF52 writes internal flash only, so the blob cannot be
dragged onto the board. --c-array emits it as a C header for a one-shot
provisioning sketch that writes it to QSPI and verifies the read-back.

Layout, little-endian:

  0x00  magic   "C2CB"
  0x04  version u16 = 1
  0x06  tables  u16 = 3
  0x08  scale   u32, milli-dB per LSB (500)
  0x0c  offset[3] u32   from start of blob
  0x18  length[3] u32   bytes
  0x24  reserved, zero to 0x40
  0x40  newamp1 stage 1, stage 2, then newamp2

Table order matches codec2_set_external_codebooks() arguments.
"""
import re
import struct
import sys

MAGIC = b"C2CB"
VERSION = 1
SCALE_MILLI_DB = 500  # 0.5 dB per LSB, must match CODEBOOK_Q8_SCALE
HEADER_LEN = 0x40

# (file, array name, expected entry count) in the order the setter takes them
TABLES = [
    ("codebooknewamp1.c", "codes0", 512 * 20),
    ("codebooknewamp1.c", "codes1", 512 * 20),
    ("codebooknewamp2.c", "codes0", 500 * 41),
]


def extract(path, array):
    """Pull one int8 array out of a generated codebook file."""
    text = open(path, encoding="utf-8", errors="ignore").read()
    # Comments carry digits (training-set filenames) and preprocessor lines sit
    # between the two declarations of each array; drop both before parsing.
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    text = re.sub(r"^\s*#.*$", " ", text, flags=re.M)
    # Each array is declared twice, once per side of an #ifdef __EMBEDDED__, so
    # take the last declaration - the one the data actually follows. Otherwise
    # the digits in the second "int8_t codes0[]" land in the values.
    starts = [m.end() for m in re.finditer(r"int8_t\s+%s\s*\[\]\s*=\s*\{" % re.escape(array), text)]
    if not starts:
        raise SystemExit("%s: array %s not found - has it been quantised?" % (path, array))
    body = text[starts[-1] : text.index("};", starts[-1])]
    vals = [int(v) for v in re.findall(r"-?\d+", body)]
    for v in vals:
        if not -128 <= v <= 127:
            raise SystemExit("%s/%s: %d does not fit in int8" % (path, array, v))
    return vals


def main():
    if len(sys.argv) not in (3, 4):
        raise SystemExit(__doc__)
    srcdir, out = sys.argv[1], sys.argv[2]
    as_c = len(sys.argv) == 4 and sys.argv[3] == "--c-array"

    blobs = []
    for fname, array, expect in TABLES:
        vals = extract("%s/%s" % (srcdir, fname), array)
        if len(vals) != expect:
            raise SystemExit("%s/%s: got %d values, expected %d" % (fname, array, len(vals), expect))
        blobs.append(struct.pack("<%db" % len(vals), *vals))
        print("%-22s %-7s %6d bytes" % (fname, array, len(vals)))

    offsets, lengths, pos = [], [], HEADER_LEN
    for b in blobs:
        offsets.append(pos)
        lengths.append(len(b))
        pos += len(b)

    header = MAGIC + struct.pack("<HHI", VERSION, len(blobs), SCALE_MILLI_DB)
    header += struct.pack("<3I", *offsets) + struct.pack("<3I", *lengths)
    header = header.ljust(HEADER_LEN, b"\0")

    blob = header + b"".join(blobs)

    if as_c:
        lines = [
            "/* Generated by tools/make_codebook_blob.py - do not edit. */",
            "#pragma once",
            "#include <stdint.h>",
            "",
            "#define CODEBOOK_BLOB_LEN %du" % len(blob),
            "",
            "static const uint8_t CODEBOOK_BLOB[CODEBOOK_BLOB_LEN] = {",
        ]
        for i in range(0, len(blob), 16):
            lines.append("    " + ", ".join("0x%02x" % c for c in blob[i : i + 16]) + ",")
        lines.append("};")
        with open(out, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
    else:
        with open(out, "wb") as f:
            f.write(blob)

    print("\n%s: %d bytes (%d header + %d tables)" % (out, pos, HEADER_LEN, pos - HEADER_LEN))


if __name__ == "__main__":
    main()
